# Построение диаграмм рассеяния

Подключение библиотек

In [26]:
%matplotlib agg #отключает автоматический вывод графиков
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import seaborn.objects as so
import numpy as np
from sklearn.metrics import mean_absolute_error
from scipy.stats import pearsonr, spearmanr, kendalltau
from scipy import stats
from scipy.stats import linregress

Чтение таблицы из файла с помощью pandas

In [27]:
file_path = "D:\\AI\\Stroop test analysis\\dataset_mental_report_new.xlsx"
data = pd.read_excel(file_path)

Вывод таблицы

In [28]:
data

,Unnamed: 0,num,marker_data_id,apway_id,context,person,gender,old,old_group,stroop_duration,...,HF_per,FR,SN,Q1,Q2,Q3,Q4,Q_common,adapt_risk,Q_edit
0,0,1,65787,1220_11316,Sofia,201,М,35,22_35,268,...,23.18,2.49,-1.03,100.0,0.0,0.0,0.0,Q1,1,0
1,1,2,65810,1226_11325,Sofia,105,М,56,36_60,836,...,74.89,0.47,1.74,0.0,78.4,21.6,0.0,Q2,6,0
2,2,3,66190,1242_11509,Sofia,106,М,60,36_60,602,...,26.65,-0.03,0.85,2.0,62.7,33.3,2.0,Q3,6,0
3,3,4,66519,1258_11745,Sofia,001test,Ж,23,22_35,136,...,5.84,-0.42,0.65,0.0,50.0,50.0,0.0,Q3,7,0
4,4,5,66555,1256_11772,Sofia,107,Ж,77,60_PLUS,472,...,70.93,0.66,2.08,0.0,100.0,0.0,0.0,Q2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,414,417,264116,5645_46265,1,eka4,Ж,60,36_60,253,...,33.03,0.36,1.56,0.0,68.8,31.2,0.0,Q2,6,0
415,415,418,264139,5623_46271,1,eka,Ж,29,22_35,139,...,22.11,-0.55,1.18,0.0,25.0,75.0,0.0,Q3,7,0
416,416,419,264233,5642_46347,1,eka3,Ж,45,36_60,236,...,15.65,1.24,0.88,0.0,100.0,0.0,0.0,Q2,5,0
417,417,420,264269,5623_46352,1,eka,Ж,29,22_35,128,...,31.79,1.02,0.67,0.0,100.0,0.0,0.0,Q2,5,0
418,418,421,264276,5666_46354,1,eka10,М,20,17_21,156,...,16.48,0.64,1.21,0.0,100.0,0.0,0.0,Q2,5,0

Выбор только нужных данных

In [29]:
necessary = data[['gender','old']]
necessary.head()

  gender  old
0      М   35
1      М   56
2      М   60
3      Ж   23
4      Ж   77

Фильтрация данных и разделение по полу.(pandas)

In [30]:
men = necessary[necessary['gender']=='М']['old']
women = necessary[necessary['gender']=='Ж']['old']

Создание графиков (matplotlib)

In [31]:
fig_width = 6.3  # Ширина
fig_height = 3.54  # Высота
plt.figure(figsize=(fig_width, fig_height), dpi=300)

bins=[10, 20, 30, 40, 50, 60, 70, 80]
plt.hist(men, bins=bins, alpha=0.5, label='Мужчины', color='blue', edgecolor='black')
#edgecolor- обводка столбцов bins- интервалы alpha- прозрачность
plt.hist(women, bins=bins, alpha=0.5, label='Женщины', color='pink', edgecolor='black')
plt.xlabel('Возраст', fontsize=13)  
plt.ylabel('Количество', fontsize=13)  
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))

Построение графиков kdeplot(график плотности распределения) для мужчин и женщин
с помощью seaborn

In [32]:
plt.figure(figsize=(fig_width, fig_height), dpi=300)
sns.kdeplot(men);
plt.title('б', loc='left')
plt.xlabel("Возраст", fontsize=13)
plt.ylabel("Плотность", fontsize=13)

Text(0, 0.5, 'Плотность')

In [33]:
plt.figure(figsize=(fig_width, fig_height), dpi=300)
sns.kdeplot(women)
plt.title('а', loc='left')
plt.xlabel("Возраст", fontsize=13)
plt.ylabel("Плотность", fontsize=13)

Text(0, 0.5, 'Плотность')

Построение графиков связи возраста с другими показателями

In [34]:
mask_covid = data['context'] == 'COVID'  #маски для фильтрации это булев массив из 0 и 1
mask_autism = data['context'] == 'Autism'
mask_rehab = data['context'] == 'Реабилитация'
mask_exoskelet = data['context'] == 'Exoskelet'
mask_Sofia = data['context'] == 'Sofia'
mask_apway = data['context'] == 'apway' 
mask_others = ~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia)
particular_column = 'old';

masks = (mask_covid, mask_autism, mask_rehab, mask_exoskelet, mask_Sofia, mask_apway, mask_others) 

particular_graphs = (5, 9, 10, 11, 12, 13, 16, 22, 23, 37, 39, 49)
for i in range(4,len(data.columns)-1):
    if (data.columns[i] != particular_column and data.columns[i] != 'person') :
        plt.figure(figsize=(16,9), dpi= 100)
        sns.scatterplot(data=data[mask_Sofia], x='old', y=data.columns[i],color='pink',label='Sofia')
        sns.scatterplot(data=data[mask_apway], x='old', y=data.columns[i],color='black',label='apway')
        sns.scatterplot(data=data[mask_covid], x='old', y=data.columns[i],color='red',label='covid')
        sns.scatterplot(data=data[mask_autism], x='old', y=data.columns[i],color='green',label='autism')
        sns.scatterplot(data=data[mask_rehab], x='old', y=data.columns[i],color='brown',label='rehab')
        sns.scatterplot(data=data[mask_exoskelet], x='old', y=data.columns[i],color="orange",label='exoskelet')
        sns.scatterplot(data=data[~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia | mask_apway)], x='old', y=data.columns[i], color='blue', label='Others')
        plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))# сдвиг легенды за график
        plt.xlabel('Age, 8 groups for each 10 years (years)')
        
       
        
        plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
        plt.close()

C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает

C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\2844240806.py:28: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show() # чтобы при каждой итерации окна не накапливались. сам график при этом не исчезает

Теперь эти графики со смещением по x

In [35]:
def scatterplots_with_offset(data, masks, y): #не доделано
    for mask in masks:
        sns.scatterplot(
        data=data[mask],
        x=data['old'][mask] + np.random.uniform(-0.5, 0.5, size=len(data[mask_Sofia])),
        y=y
        )

In [36]:
def save_plots(i, particular_graphs):
    if (i in particular_graphs):
            column_number = str(i).zfill(2)
            plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot/particular/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
    else:
        column_number = str(i).zfill(2)
        plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
    # plt.gca().invert_yaxis()  инвертировать y для олд груп например

In [37]:


particular_graphs = (5, 9, 10, 11, 12, 13, 16, 22, 23, 37, 39, 49)

#для того чтобы в графике old_group группы шли по порядку сделаем отдельный случай
age_groups_order = ['4_7', '8_12', '13_16', '17_21', '22_35', '36_60', '60_PLUS']

#используется для преобразования столбца data['old_group'] в категориальный тип данных с явным порядком категорий.
#ordered=True — указывает, что категории имеют явный порядок, который следует учитывать при построении графиков 
data['old_group'] = pd.Categorical(data['old_group'], categories=age_groups_order, ordered=True)   

color_dict = sns.color_palette("bright", n_colors=7)  # 6 цветов для различных контекстов

for i in range(9, len(data.columns)-1):
    if (data.columns[i] != particular_column and data.columns[i] != 'person' and data.columns[i] != 'Q_common'): 
        
        plt.figure(figsize=(fig_width, fig_height), dpi=300)
        
        
        sns.scatterplot(
        data=data[mask_Sofia], 
        x=data['old'][mask_Sofia] + np.random.uniform(-0.5, 0.5, size=len(data[mask_Sofia])),# передается как данные
        y=data.columns[i],#передаётся как название солбца
        label='София',
        color=color_dict[0]
    )
        
        # последнее значит что точки не рис(уже есть)
        sns.regplot(data=data[mask_Sofia], color=color_dict[0], x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        
        sns.scatterplot(
        data=data[mask_covid], 
        x=data['old'][mask_covid] + np.random.uniform(-0.5, 0.5, size=len(data[mask_covid])), 
        y=data.columns[i],
        label='Ковид',
        color=color_dict[2]
    )
        sns.regplot(data=data[mask_covid],color=color_dict[2], x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        sns.scatterplot(
        data=data[mask_autism], 
        x=data['old'][mask_autism] + np.random.uniform(-0.5, 0.5, size=len(data[mask_autism])), 
        y=data.columns[i],
        label='Аутизм',
        color='black'
    )
        #sns.regplot(ci=None, data=data[mask_autism], color='black', x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        sns.scatterplot(
        data=data[mask_rehab], 
        x=data['old'][mask_rehab] + np.random.uniform(-0.5, 0.5, size=len(data[mask_rehab])), 
        y=data.columns[i], 
        label='Рехаб',
        color='orange'
    )
        sns.regplot(data=data[mask_rehab], color='orange', x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        sns.scatterplot(
        data=data[mask_exoskelet], 
        x=data['old'][mask_exoskelet] + np.random.uniform(-0.5, 0.5, size=len(data[mask_exoskelet])), 
        y=data.columns[i],
        label='Экзоскелет',
        color=color_dict[5]
    )
        sns.regplot(data=data[mask_exoskelet], color=color_dict[5], x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        sns.scatterplot(
        data=data[~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia)],
        x=data['old'][~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia) ] + 
        np.random.uniform(-0.5, 0.5, size=len(data[~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia) ])),
        y=data.columns[i],
        label='Другие',
        color=color_dict[6]
    )
        sns.regplot(
            data=data[~(mask_covid | mask_autism | mask_rehab | mask_exoskelet | mask_Sofia )],
            color=color_dict[6],
            x='old', y=data.columns[i],
            line_kws={'linewidth': 2},
            scatter=False  
            
    )
            
           
        if i == 9:
            plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))# сдвиг легенды за график
            plt.xlabel('Возраст, 8 групп по 10 лет (года)', fontsize=14, fontweight='light')
            plt.ylabel('Продолжительность теста', fontsize=14, fontweight='light')
            plt.title('а', loc='left')
        else:
            plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))# сдвиг легенды за график
            plt.xlabel('Age, 8 groups for each 10 years (years)', fontsize=14, fontweight='light')
            plt.ylabel(data.columns[i], fontsize=14, fontweight='light')
        '''
        #сохраниение
        if (i in particular_graphs):
            column_number = str(i).zfill(2)
            plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot/particular/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
        else:
            column_number = str(i).zfill(2)
            plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
        # plt.gca().invert_yaxis()  инвертировать y для олд груп например
        '''
        plt.show()
        plt.close()

C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\3000593757.py:103: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Построение такого же набора графиков, но раскрашиваются мужчины и женщины

In [38]:
mask_men = data['gender'] == 'М'
mask_women = data['gender'] == 'Ж'
particular_graphs = (13, 14, 15, 37, 43, 45, 47, 48)

for i in range(9,len(data.columns)-1):
    if (data.columns[i] != particular_column and data.columns[i] != 'person' and data.columns[i] != 'Q_common') :
        #plt.figure(figsize=(16,9), dpi= 200)
        plt.figure(figsize=(fig_width, fig_height), dpi=300)
        
        sns.scatterplot(
            data=data[mask_men], 
            x=data['old'][mask_men] + np.random.uniform(-0.5, 0.5, size=len(data[mask_men])), 
            y=data.columns[i],
            color="blue",label='Мужчины'
        )
        sns.regplot(data=data[mask_men], color='blue', x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        
        sns.scatterplot(
            data=data[mask_women], 
            x=data['old'][mask_women] + np.random.uniform(-0.5, 0.5, size=len(data[mask_women])), 
            y=data.columns[i],
            color="red",label='Женщины'
        )
        sns.regplot(data=data[mask_women], color='red', x='old', y=data.columns[i], line_kws={'linewidth': 2}, scatter=False)

        
        if i == 9:
            plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))# сдвиг легенды за график
            plt.xlabel('Возраст, 8 групп по 10 лет (года)', fontsize=14, fontweight='light')
            plt.ylabel('Продолжительность теста', fontsize=14, fontweight='light')
            plt.title('б', loc='left')
        else:
            plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))# сдвиг легенды за график
            plt.xlabel('Age, 8 groups for each 10 years (years)', fontsize=14, fontweight='light')
            plt.ylabel(data.columns[i], fontsize=14, fontweight='light')
        
        #сохраниение
        '''
        if (i in particular_graphs):
            column_number = str(i).zfill(2)
            plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot_1/particular/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
        else:
            column_number = str(i).zfill(2)
            plt.savefig(f'D:/AI/HIstogram/scat_vith_regplot_1/plot_{column_number}_{data.columns[i]}_vs_{particular_column}.png', format='png', dpi=600)
        '''
        plt.show()
        plt.close()

C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
C:\Users\kirya\AppData\Local\Temp\ipykernel_24580\1948071864.py:47: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()